diff a/arch/arm/boot/dts/Makefile b/arch/arm/boot/dts/Makefile	(rejected hunks)
@@ -897,6 +897,15 @@ dtb-$(CONFIG_ARCH_VT8500) += \
	wm8650-mid.dtb \
	wm8750-apc8750.dtb \
	wm8850-w70v2.dtb
+dtb-$(CONFIG_ARCH_AXXIA) += axm5504-sim-mmc.dtb \
+	axm5504-sim-virtio.dtb \
+	axm5516-sim-mmc.dtb \
+	axm5516-sim-virtio.dtb \
+	axm5504-emu.dtb \
+	axm5507-emu.dtb \
+	axm5516-amarillo.dtb \
+	axm5512-amarillo.dtb \
+	axm5508-amarillo.dtb
 dtb-$(CONFIG_ARCH_ZYNQ) += \
	zynq-parallella.dtb \
	zynq-zc702.dtb \
